### ISSUE TITLE
咨询一下文章EM算法的具体使用方式

### ISSUE THREAD

**Issue by ithok** [wyl7/ClusterSCL#1]
作者您好，感谢您的工作！
想问的是关于文章4.2节的EM算法，具体是怎么体现在整个模型的优化过程中，因为我个人对这部分很难理解。
具体来说，就是EM算法固定了什么 E-step在干什么 M-step在干什么 怎么体现到模型的优化中
可能问题有些低级，但还是望您不吝赐教。
祝您工作顺利。

**Comment by wyl7** [comment]
> 作者您好，感谢您的工作！ 想问的是关于文章4.2节的EM算法，具体是怎么体现在整个模型的优化过程中，因为我个人对这部分很难理解。 具体来说，就是EM算法固定了什么 E-step在干什么 M-step在干什么 怎么体现到模型的优化中 可能问题有些低级，但还是望您不吝赐教。 祝您工作顺利。

读者您好，非常感谢您关注我们的工作。针对你的问题，我们求解的任务可以抽象为一个log likelihood maximization的任务，具体求解过程中使用到了变分EM。具体，引入变分q去近似后验概率，在E-step我们用公式（11）计算q，在M-step，基于E-step计算的结果进一步计算log likelihood的evidence lower bound，并以最大化下界为目标优化模型参数。特别地，在我们的工作中，变分参数和似然函数的参数是共享的（都是encoder的参数），所以我们两步进行了统一的优化。
您可以给我发邮件，我可以分享之前整理的笔记，谢谢。

**Comment by ithok** [comment]
抱歉因为一些原因没能即时看到您的回复，已经给您文章预留的邮箱发送了邮件，非常感谢！
